name: Deploy Web Assembly

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup GO
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build static files
        id: build
        run: |
          mkdir -p web
          go build -o web/game.wasm ./cmd

          cp $(go env GOROOT)/misc/wasm/wasm_exec.js web/
        env:
          GOOS: js
          GOARCH: wasm

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
